######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################



TEMPLATE = app
TARGET = bin/spring

CONFIG += qt 
QT += xml gui opengl core


PKGCONFIG += luabind lua5.1
LIBS += -lqglviewer-qt4  -lcore -lmath -lgeo -lgl -lphys -lGLEW  -ltool  -lgui -lscript -lgomp


SOURCES += main.cpp 


#CONFIG += debug



