######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################


TEMPLATE = app
TARGET = bin/kinect

CONFIG += qt 
QT += xml gui opengl core

LIBS += -lqglviewer-qt4  -lcore -lmath  -lgeo -lgl -lphys -lGLEW  -ltool -lmocap  -lgui -lscript -lgomp -limage -lplugin

LIBS += -lmeuh

PKGCONFIG += luabind lua5.1

SOURCES += main.cpp 


#CONFIG += debug



