* Download

: sudo apt-get install git qt4-qmake
:  git clone git://gitorious.org/meuh/meuh.git
  
* Dependencies
  
  The following command should take care of build-deps automagically
  on the latest Ubuntu/Debian:

:  cd meuh
:  qmake
:  make deps
  
  If you only need the runtime depenendencies, run =make deps= instead.

  A [[http://www.mosek.com/][MOSEK]] plugin can be optionally compiled (see plugin/mosek/ )
  
* Customize build
  
  Have a look at the custom build file =build/custom.pro.example=, and
  save overrides in =meuh/build/custom.pro=.

  Also, edit =app/app.pro= to select which sub-projects to build.
	
* Build

  This should do it:
  
:  cd meuh
:  qmake
:  make -k

  libs end up in =./lib=, binaries in =./bin=
  
* Run 

The =master= branch will only build the =balance= sub-project, which
implements PGA-based character control.

You need to declare the =MEUH_PATH= environment variable to be the
root of the repository, and add =$MEUH_PATH/lib= to =LD_LIBRARY_PATH=,
/e.g./ by putting this in =~/.bashrc=:

: export MEUH_PATH=/the/path/to/meuh
: export LD_LIBRARY_PATH=$MEUH_PATH/lib:$LD_LIBRARY_PATH

Run =bin/balance=, then use mouse to control camera, shit+mouse to
interact with the virtual character, press =r= to reset simulation.

Have fun :-)
   
  
