######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################


TEMPLATE = app
TARGET = limits

include(../../common.pro)

CONFIG += qt 
QT += xml gui opengl core

LIBS += -lqglviewer-qt4 -L../lib -lcore -lmath  -lmocap -lgl -lphys -lGLEW -lcontrol -ltool -lgui

SOURCES += limits.cpp 

#CONFIG += debug



