######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################


TEMPLATE = app
TARGET = mesh

include(../common.pro)


CONFIG += qt
QT += xml gui opengl core

LIBS += -lqglviewer-qt4 -L../lib -lcore -lmath  -lgeo -lmocap -lgl -lphys -lGLEW # -lmosek

HEADERS += viewer/mesh.h
SOURCES += main.cpp viewer/mesh.cpp 




