######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################


TEMPLATE = app
TARGET = clip

include(../../common.pro)


CONFIG += qt
QT += xml gui opengl core

LIBS += -lqglviewer-qt4 -lcore  -lmocap -lgl -lphys -lGLEW -lgeo -lcontrol  -lscript -ltool -lgui -lmath -lgomp 

HEADERS += clip_viewer.h
SOURCES += clip.cpp clip_viewer.cpp 


