######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################



TEMPLATE = app
TARGET = bin/script

CONFIG += qt
QT += xml gui opengl core

PKGCONFIG += lua5.1

LIBS +=  -ltool -lgui -lscript -lluabind -lcore -lboost_program_options -lgomp

SOURCES += main.cpp

#CONFIG += debug



