######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################

TEMPLATE = app
TARGET = bin/screw


CONFIG += qt
QT += xml gui opengl core

LIBS += -lqglviewer-qt4 -lgl -lGLEW -lmath -lcore -ltool -lgui -lpthread -lgeo -lmocap -lphys -lscript -lgomp

HEADERS += \
           screw_viewer.h \
   
SOURCES += \
    screw.cpp \
    screw_viewer.cpp \


