######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################



TEMPLATE = app
TARGET = ellipsoid

include(../../common.pro)

CONFIG += qt
QT += xml gui opengl core

LIBS +=  -ltool -lgl -lgui -lphys -lscript -lgeo -lmocap -lmath -lcore -lcontrol -lgomp -lqglviewer-qt4

SOURCES += ellipsoid.cpp 

#CONFIG += debug



