######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 24 00:05:30 2010
######################################################################

TEMPLATE = lib
TARGET = lib/coll

SOURCES += \
    primitive.cpp \
    system.cpp \
    hit.cpp \
    group.cpp \
    hierarchy.cpp \
    