######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 24 00:05:30 2010
######################################################################

TEMPLATE = lib
TARGET = lib/geo

SOURCES += \
    error.cpp \
    obj/file.cpp \
    obj.cpp \
    mesh.cpp \
    plane.cpp \
    sphere.cpp \
    aabb.cpp \
    octree.cpp \
    
 