######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 3 15:50:58 2010
######################################################################

TEMPLATE = app
TARGET = test


include(../../common.pro)

# QMAKE_CXX=/usr/lib/gcc-snapshot/bin/g++


CONFIG += qt
QT += xml gui opengl core

LIBS += -lqglviewer-qt4  -lcore -lmath  -lgeo -lgl -lphys -lGLEW  -ltool -lmocap -lcontrol -lgui -lgomp

SOURCES += main.cpp test1.cpp

#CONFIG += debug



