######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 24 00:05:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . .. /usr/local/include/eigen3

# Input
HEADERS += 

SOURCES += load_obj.cpp obj/file.cpp vbo.cpp

LIBS += -lGLEW -lmath -lgl -L../lib

QMAKE_CXXFLAGS += -std=c++0x

